version: "3"
services:
  mongodb:
    image: mongo:5.0
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ~/apps/mongo-ecofood:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ecofood-dev
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
  ecofood-back:
    image: ecofood-back-img
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    ports:
      - 2000:${PORT}
    tty: true
